### ISSUE TITLE
problems normalizing paths causes test failures in django-oscar

### ISSUE THREAD

**Issue by apotterri** [getappmap/appmap-python#227]
Running the tests in [django-oscar](https://github.com/django-oscar/django-oscar) with v1.14.0 of appmap-python shows 4 failures:
```
FAILED tests/unit/catalogue/test_views_reviews.py::TestAddVoteView::test_voting_on_product_review_redirect_on_public_product - re.error: unbalanced parenthesis at position 71
FAILED tests/unit/catalogue/test_views_reviews.py::TestAddVoteView::test_voting_on_product_review_returns_404_on_non_public_product - re.error: unbalanced parenthesis at position 71
FAILED tests/unit/catalogue/test_views_reviews.py::TestProductReviewDetail::test_retrieving_product_review_returns_200_on_public_product - RuntimeError: No match for /catalogue/dumu03fbu03a5-title_12/reviews/70/ found with resolver <URLResolver 'tests._site.urls' (None:None) '^/'>, regex ^catalogue/\(\...
FAILED tests/unit/catalogue/test_views_reviews.py::TestProductReviewDetail::test_retrieving_product_review_returns_404_on_non_public_product - RuntimeError: No match for /catalogue/dumu03fbu03a5-title_13/reviews/71/ found with resolver <URLResolver 'tests._site.urls' (None:None) '^/'>, regex ^catalogue/\(\...
```

One of the failure stack traces:
```
ERROR    django.request:log.py:224 Internal Server Error: /catalogue/dumu03fbu03a5-title_13/reviews/71/
Traceback (most recent call last):
  File "/Users/ajp/src/django-oscar/django-oscar/.direnv/python-3.10.8/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/ajp/src/django-oscar/django-oscar/.direnv/python-3.10.8/lib/python3.10/site-packages/appmap/django.py", line 236, in __call__
    rec, start, call_event_id = self.before_request_hook(request, request.path_info)
  File "/Users/ajp/src/django-oscar/django-oscar/.direnv/python-3.10.8/lib/python3.10/site-packages/_appmap/web_framework.py", line 170, in before_request_hook
    start, call_event_id = self.before_request_main(rec, request)
  File "/Users/ajp/src/django-oscar/django-oscar/.direnv/python-3.10.8/lib/python3.10/site-packages/appmap/django.py", line 270, in before_request_main
    normalized_path_info = normalize_path_info(req.path_info, resolved)
  File "/Users/ajp/src/django-oscar/django-oscar/.direnv/python-3.10.8/lib/python3.10/site-packages/appmap/django.py", line 195, in normalize_path_info
    regex, match = get_resolved_match(path_info, resolver)
  File "/Users/ajp/src/django-oscar/django-oscar/.direnv/python-3.10.8/lib/python3.10/site-packages/appmap/django.py", line 181, in get_resolved_match
    raise RuntimeError(
RuntimeError: No match for /catalogue/dumu03fbu03a5-title_13/reviews/71/ found with resolver <URLResolver 'tests._site.urls' (None:None) '^/'>, regex ^catalogue/\(\?P(?P<product_slug>[^/]+)\[\\w\-\]\*\)_\(\?P(?P<product_pk>[^/]+)\\d\+\)/reviews/(?P<pk>[0-9]+)/
```
`

**Comment by symwell** [comment]
An observation on the unbalanced parenthesis error: [src/oscar/apps/catalogue/reviews/apps.py:get_urls()](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/reviews/apps.py#L26) contains an extra parenthesis.

```
path('<int:pk>)/vote/', login_required(self.vote_view.as_view()), name='reviews-vote'),
```
