### ISSUE TITLE
appmap seems to interfere with installation of scikit-learn

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-python#311]
```
(sckit-learn) (base) ➜  scikit-learn git:(main) ✗ pip install -e .
Obtaining file:///Users/kgilpin/source/land-of-apps/scikit-learn
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<frozen runpy>", line 131, in _get_module_details
        File "<frozen importlib.util>", line 100, in find_spec
        File "<frozen importlib._bootstrap>", line 1262, in _find_spec
        File "/Users/kgilpin/source/land-of-apps/scikit-learn/sckit-learn/lib/python3.12/site-packages/_appmap/wrapt/wrappers.py", line 622, in __call__
          return self._self_wrapper(self.__wrapped__, self._self_instance,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kgilpin/source/land-of-apps/scikit-learn/sckit-learn/lib/python3.12/site-packages/_appmap/importer.py", line 249, in wrapped_find_spec
          spec = find_spec(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: 'classmethod' object is not callable
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/Users/kgilpin/source/land-of-apps/scikit-learn/sckit-learn/lib/python3.12/site-packages/pip/__pip-runner__.py", line 50, in <module>
          runpy.run_module("pip", run_name="__main__", alter_sys=True)
        File "<frozen runpy>", line 222, in run_module
        File "<frozen runpy>", line 140, in _get_module_details
      ImportError: Error while finding module specification for 'pip' (TypeError: 'classmethod' object is not callable)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

With appmap uninstalled from pip, I do not get this error.

**Comment by apotterri** [comment]
This is resolved by disabling recording by default (i.e. by [v2](https://pypi.org/project/appmap/2.0.0/)).
