### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-python#322]
Found in [`sympy` v1.0](https://github.com/sympy/sympy/tree/sympy-1.0) test cases.
```
Traceback (most recent call last):
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/utilities/runtests.py", line 1130, in wrapper
    test_func()
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/functions/special/tests/test_zeta_functions.py", line 95, in test_derivatives
    assert zeta(x, a).diff(x) == Derivative(zeta(x, a), x)
  File "/home/db/dev/applandinc/appmap-python/_appmap/wrapt/wrappers.py", line 712, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 129, in instrumented_fn
    return call_instrumented(f, instance, args, kwargs)
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 92, in call_instrumented
    ret = f.fn(*args, **kwargs)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/core/expr.py", line 2949, in diff
    return Derivative(self, *new_symbols, **assumptions)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/core/function.py", line 1187, in __new__
    obj = expr._eval_derivative(v)
  File "/home/db/dev/applandinc/appmap-python/_appmap/wrapt/wrappers.py", line 712, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 129, in instrumented_fn
    return call_instrumented(f, instance, args, kwargs)
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 92, in call_instrumented
    ret = f.fn(*args, **kwargs)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/core/function.py", line 559, in _eval_derivative
    df = self.fdiff(i)
  File "/home/db/dev/applandinc/appmap-python/_appmap/wrapt/wrappers.py", line 712, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 129, in instrumented_fn
    return call_instrumented(f, instance, args, kwargs)
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 103, in call_instrumented
    event.ExceptionEvent(
  File "/home/db/dev/applandinc/appmap-python/_appmap/event.py", line 509, in __init__
    {"class": fqname(class_), "message": str(exc), "object_id": id(exc)}
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/core/function.py", line 94, in __str__
    (self.args[1], self.args[0]))
IndexError: tuple index out of range
```

**Comment by apotterri** [comment]
>  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/core/function.py", line 94, in __str__
This is in `ArgumentIndexError.__str__`, where `ArgumentIndexError` is defined as
```
class ArgumentIndexError(ValueError):
```
sympy 1.0 was testing python 2.6 through 3.5: https://github.com/sympy/sympy/blob/sympy-1.0/.travis.yml#L13 , but SWE-bench was using 3.9.

We should investigate whether using 3.9 was the root cause of this problem.
