### ISSUE TITLE
Installing appmap breaks Microsoft's VS Code python extension support for starting a REPL 

### ISSUE THREAD

**Issue by apotterri** [getappmap/appmap-python#339]
If you install `appmap` into the virtual environment selected for a project, trying to start a REPL (with the command `python.execInREPL`, which is bound to `shift+enter` by default) will fail.

Turning on logging for `vscode-python` shows the stack trace:
```
2024-06-14 09:22:29.976 [error] Error: Error processing line 1 of /opt/anaconda3/envs/python-test/lib/python3.9/site-packages/appmap.pth:


	at s (/Users/ajp/.vscode/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:224147)
	at Socket.<anonymous> (/Users/ajp/.vscode/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:224443)
	at Socket.emit (node:events:514:28)
	at addChunk (node:internal/streams/readable:376:12)
	at readableAddChunk (node:internal/streams/readable:349:9)
	at Readable.push (node:internal/streams/readable:286:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```
in the "Extension Host" output.

**Comment by Incantatoric** [comment]
I have the same problem with the appmap vscode extension. shift+enter refused to start REPL with poetry, and removing the following appmap line from pyproject.toml solved the problem:

`appmap = {version = "^2.0.8", allow-prereleases = true}`

Then I ran `poetry update`, and it removed appmap (2.0.8), importlib-resources (5.13.0), and inflection (0.5.1), which solved the issue.

**Comment by apotterri** [comment]
@Incantatoric v2.0.9 has been released now with a fix for this problem.
