### ISSUE TITLE
ImportError: cannot import name '_thread' from 'moves' (unknown location)

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-python#369]
https://github.com/getappmap/SWE-bench/actions/runs/10354682656/job/28660536027#step:7:4432

```
Traceback (most recent call last):
  File "/home/runner/work/SWE-bench/SWE-bench/solver/solve/solver.py", line 20, in <module>
    from solve.steps.build_task_manager import build_task_manager
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/home/runner/work/SWE-bench/SWE-bench/solver/solve/../solve/steps/build_task_manager.py", line 3, in <module>
    from swebench.harness.context_manager import TaskEnvContextManager
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/home/runner/work/SWE-bench/SWE-bench/swebench/__init__.py", line 15, in <module>
    from swebench.harness.run_evaluation import (
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/home/runner/work/SWE-bench/SWE-bench/swebench/harness/run_evaluation.py", line 5, in <module>
    import datasets
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/datasets/__init__.py", line 17, in <module>
    from .arrow_dataset import Dataset
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 59, in <module>
    import pandas as pd
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "interval.pyx", line 1, in init pandas._libs.interval
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "missing.pyx", line 1, in init pandas._libs.missing
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/pandas/_libs/tslibs/__init__.py", line 40, in <module>
    from pandas._libs.tslibs.conversion import localize_pydatetime
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "timedeltas.pyx", line 1, in init pandas._libs.tslibs.timedeltas
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "timezones.pyx", line 24, in init pandas._libs.tslibs.timezones
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/wrapt/wrappers.py", line 620, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/_appmap/importer.py", line 279, in wrapped_exec_module
    exec_module(*args, **kwargs)
  File "/usr/share/miniconda/envs/swe-bench/lib/python3.9/site-packages/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
ImportError: cannot import name '_thread' from 'moves' (unknown location)

```

**Comment by apotterri** [comment]
This error also occurs when run without the agent. Closing this in favor of https://github.com/getappmap/SWE-bench/issues/98 .
